(function(){
"use strict";
const APP_VERSION="1.6.0",SCHEMA_VERSION=1;
const KEYS={user:"demae.user",config:"demae.config",ledger:"demae.ledger",records:"demae.records",submissions:"demae.submissions",preferences:"demae.preferences",system:"demae.system"};
const $=id=>document.getElementById(id),now=()=>new Date().toISOString();
const localDate=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const envelope=(data)=>({schemaVersion:SCHEMA_VERSION,updatedAt:now(),data});
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key))?.data??fallback}catch{return fallback}}
function save(key,data){localStorage.setItem(key,JSON.stringify(envelope(data)))}
function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
let user=load(KEYS.user,{}),config=load(KEYS.config,{workers:[],recipientEmail:""}),ledger=load(KEYS.ledger,{version:"未設定",items:[]}),records=load(KEYS.records,[]),submissions=load(KEYS.submissions,[]),prefs=load(KEYS.preferences,{transportHistory:[],lastSite:""});
let editingId=null,selectedTransport=[];
save(KEYS.system,{appVersion:APP_VERSION});
function esc(v){return String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function show(view){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$(view).classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.view===view));if(view==="historyView")renderHistory();if(view==="submitView")renderSubmit()}
document.querySelectorAll(".tab").forEach(x=>x.onclick=()=>show(x.dataset.view));
function setToday(){$("workDate").value=localDate();$("submitDate").value=localDate();$("historyMonth").value=localDate().slice(0,7)}
function calc(){const c=DemaeCalc.calculate($("startTime").value,$("endTime").value,$("workType").value);$("normalDisplay").textContent=c.normalDisplay;$("overtimeDisplay").textContent=c.overtimeDisplay;$("nightDisplay").textContent=c.nightDisplay;return c}
function setShift(){if($("shift").value==="night"){$("startTime").value="20:00";$("endTime").value="05:00"}else if($("shift").value==="day"){$("startTime").value="08:00";$("endTime").value="17:00"}calc()}
[$("startTime"),$("endTime")].forEach(x=>x.addEventListener("input",calc));$("workType").addEventListener("change",calc);$("shift").addEventListener("change",setShift);$("department").addEventListener("change",renderSites);
function renderSites(){const current=$("site").value,dep=$("department").value;$("site").innerHTML='<option value="">現場なし</option>';ledger.items.filter(x=>x.department===dep).forEach(x=>{const o=document.createElement("option");o.value=x.code;o.textContent=x.name;o.dataset.name=x.name;$("site").appendChild(o)});if([...$("site").options].some(x=>x.value===current))$("site").value=current;else if(prefs.lastSite&&[...$("site").options].some(x=>x.value===prefs.lastSite))$("site").value=prefs.lastSite}
function renderTransport(){$("transportHistory").innerHTML=prefs.transportHistory.map(x=>`<option value="${esc(x)}">`).join("");$("transportTags").innerHTML="";selectedTransport.forEach((name,i)=>{const b=document.createElement("button");b.type="button";b.className="tag";b.textContent=name+" ×";b.onclick=()=>{selectedTransport.splice(i,1);renderTransport()};$("transportTags").appendChild(b)});$("transportToggle").textContent=selectedTransport.length?`送迎：${selectedTransport.join("、")}`:"送迎を入力"}
$("transportToggle").onclick=()=>$("transportPanel").classList.toggle("open");$("transportAdd").onclick=()=>{const n=$("transportName").value.trim();if(!n)return;if(!prefs.transportHistory.includes(n))prefs.transportHistory.unshift(n);if(!selectedTransport.includes(n))selectedTransport.push(n);save(KEYS.preferences,prefs);$("transportName").value="";renderTransport()};
function selectedSiteName(){const o=$("site").selectedOptions[0];return o?.dataset.name||"現場なし"}
function resetForm(){editingId=null;$("editBanner").classList.add("hidden");$("saveRecord").textContent="保存して確認";$("workDate").value=localDate();$("shift").value="day";$("workType").value="通常";$("department").value=user.department||"舗装";$("commute").value=0;$("meals").value=0;$("specialA").value=0;$("specialB").value=0;$("note").value="";selectedTransport=[];$("transportPanel").classList.remove("open");setShift();renderSites();renderTransport()}
$("cancelEdit").onclick=resetForm;
$("saveRecord").onclick=()=>{
  if(!user.employeeId||!user.name){alert("先に設定画面で社員番号と氏名を登録してください。");show("settingsView");return}
  if(!Number.isInteger(Number($("commute").value))||Number($("commute").value)<0){alert("通勤は0以上の整数で入力してください。");return}
  const siteCode=$("site").value,note=$("note").value.trim(),absence=["休日","雨休","特休","有給"].includes($("workType").value);if(!siteCode&&!note&&!absence){alert("現場なしの場合は、摘要へ内容を入力してください。");return}
  const previous=records.find(x=>x.recordId===editingId),c=calc(),stamp=now();
  const r={recordId:editingId||uid(),schemaVersion:SCHEMA_VERSION,employeeId:user.employeeId,employeeName:user.name,workDate:$("workDate").value,targetMonth:$("workDate").value.slice(0,7),shift:$("shift").value,workType:$("workType").value,department:$("department").value,siteCode,siteName:selectedSiteName(),startTime:$("startTime").value,endTime:$("endTime").value,crossesMidnight:$("endTime").value<=$("startTime").value,breakMinutes:90,commute:Number($("commute").value||0),transport:[...selectedTransport],meals:Number($("meals").value||0),specialA:Number($("specialA").value||0),specialB:Number($("specialB").value||0),note,...c,createdAt:previous?.createdAt||stamp,updatedAt:stamp,revision:(previous?.revision||0)+1,status:previous?.status==="submitted"?"modified":"draft",deleted:false};
  if(previous)records=records.map(x=>x.recordId===r.recordId?r:x);else records.push(r);prefs.lastSite=siteCode;save(KEYS.records,records);save(KEYS.preferences,prefs);resetForm();show("historyView");
};
function dayRecords(date,includeDeleted=false){return records.filter(x=>x.workDate===date&&(includeDeleted||!x.deleted))}
function totals(list){return list.reduce((a,r)=>(a.days.add(r.workDate),a.normal+=r.normalMinutes,a.ot+=r.overtimeMinutes,a.night+=r.nightMinutes,a),{days:new Set(),normal:0,ot:0,night:0})}
function renderHistory(){const month=$("historyMonth").value,list=records.filter(x=>x.targetMonth===month&&!x.deleted).sort((a,b)=>b.workDate.localeCompare(a.workDate)||b.updatedAt.localeCompare(a.updatedAt)),t=totals(list);$("historySummary").textContent=`勤務日数 ${t.days.size}日／平時 ${DemaeCalc.display(t.normal)}／残業 ${DemaeCalc.display(t.ot)}／深夜 ${DemaeCalc.display(t.night)}`;$("historyList").innerHTML=list.length?"":'<div class="card">この月の入力はありません。</div>';list.forEach(r=>{const d=document.createElement("div");d.className="record";const state=r.status==="submitted"?'<span class="badge sent">提出済み</span>':r.status==="modified"?'<span class="badge">再提出必要</span>':'<span class="badge">未提出</span>';d.innerHTML=`<h3>${esc(r.workDate)}　${r.shift==="night"?"夜":"昼"} ${state}</h3><div class="meta"><div>${esc(r.department)}</div><div>${esc(r.siteName)}</div><div>${esc(r.startTime)}～${esc(r.endTime)}</div><div>通勤 ${esc(r.commute)}</div><div>平時 ${esc(r.normalDisplay)}</div><div>残業 ${esc(r.overtimeDisplay)}</div><div>深夜 ${esc(r.nightDisplay)}</div><div>送迎 ${esc(r.transport.join("、")||"なし")}</div></div><p>${esc(r.note)}</p><div class="record-actions"><button class="btn sub edit">編集</button><button class="btn danger remove">削除</button></div>`;d.querySelector(".edit").onclick=()=>editRecord(r.recordId);d.querySelector(".remove").onclick=()=>deleteRecord(r.recordId);$("historyList").appendChild(d)})}
$("historyMonth").onchange=renderHistory;
function editRecord(id){const r=records.find(x=>x.recordId===id);if(!r)return;editingId=id;$("editBanner").classList.remove("hidden");$("saveRecord").textContent="修正を保存";$("workDate").value=r.workDate;$("shift").value=r.shift;$("workType").value=r.workType;$("department").value=r.department;renderSites();$("site").value=r.siteCode;$("startTime").value=r.startTime;$("endTime").value=r.endTime;$("commute").value=r.commute;$("meals").value=r.meals;$("specialA").value=r.specialA;$("specialB").value=r.specialB;$("note").value=r.note;selectedTransport=[...r.transport];renderTransport();calc();show("inputView")}
function deleteRecord(id){const r=records.find(x=>x.recordId===id);if(!r||!confirm("この入力を削除しますか？"))return;if(r.status==="submitted"||r.status==="modified"){r.deleted=true;r.status="deleted";r.updatedAt=now();r.revision+=1;alert("提出済みの記録です。本日分を再提出してください。")}else records=records.filter(x=>x.recordId!==id);save(KEYS.records,records);renderHistory()}
function renderUser(){const preset=user.employeeId&&user.name?`${user.employeeId}|${user.name}`:"";$("employeePreset").innerHTML=config.workers.length?'<option value="">選択してください</option>':'<option value="">初期設定ファイルを読み込んでください</option>';config.workers.forEach(w=>{const o=document.createElement("option");o.value=`${w.employeeId}|${w.name}`;o.textContent=`${w.employeeId}　${w.name}`;$("employeePreset").appendChild(o)});$("employeePreset").value=[...$("employeePreset").options].some(x=>x.value===preset)?preset:"";$("employeeId").value=user.employeeId||"";$("employeeName").value=user.name||"";$("userDepartment").value=user.department||"舗装";$("recipientEmail").value=user.recipientEmail||config.recipientEmail||"";$("ledgerStatus").textContent=`現在の工事台帳：${ledger.version}（${ledger.items.length}件）`;$("statusLine").textContent=user.name?`${user.name}／台帳 ${ledger.version}`:"最初に利用者設定をしてください";$("currentWorker").textContent=user.name?`${user.employeeId} ${user.name}`:"未設定"}
$("employeePreset").onchange=()=>{const [id="",name=""]=$("employeePreset").value.split("|");$("employeeId").value=id;$("employeeName").value=name};
$("chooseSetup").onclick=()=>$("setupFile").click();
$("setupFile").onchange=async()=>{const f=$("setupFile").files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x.workers)||!x.workers.length||!x.recipientEmail)throw new Error("必要な設定がありません");config={version:String(x.version||localDate()),workers:x.workers.map(w=>({employeeId:String(w.employeeId||""),name:String(w.name||"")})).filter(w=>w.employeeId&&w.name),recipientEmail:String(x.recipientEmail)};if(!config.workers.length)throw new Error("利用者がありません");save(KEYS.config,config);renderUser();alert("初期設定を読み込みました。自分の名前を選んでください。")}catch(e){alert("初期設定ファイルを読み込めませんでした。\n"+e.message)}finally{$("setupFile").value=""}};
$("saveUser").onclick=()=>{const employeeId=$("employeeId").value.trim(),name=$("employeeName").value.trim(),recipientEmail=$("recipientEmail").value.trim();if(!employeeId||!name){alert("社員番号と氏名を入力してください。");return}user={employeeId,name,department:$("userDepartment").value,recipientEmail,initializedAt:user.initializedAt||now(),updatedAt:now()};save(KEYS.user,user);renderUser();resetForm();alert("利用者設定を保存しました。");};
function parseCsv(text){const rows=[];let row=[],cell="",quote=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'&&quote&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')quote=!quote;else if(ch===','&&!quote){row.push(cell);cell=""}else if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x!==""))rows.push(row);row=[];cell=""}else cell+=ch}row.push(cell);if(row.some(x=>x!==""))rows.push(row);return rows}
function normalizeLedger(raw,fileName){let version=localDate(),items=[];if(fileName.toLowerCase().endsWith(".json")){const obj=JSON.parse(raw);version=String(obj.version||obj.ledgerVersion||version);const list=Array.isArray(obj)?obj:(obj.items||obj.data||[]);items=list.map(x=>({department:String(x.department||x.category||x.部門||"その他"),code:String(x.code||x.工事コード||""),name:String(x.name||x.工事名称||x.工事名||"")}))}else{const rows=parseCsv(raw.replace(/^\uFEFF/,"")),head=rows.shift().map(x=>x.trim()),idx=(...names)=>head.findIndex(h=>names.includes(h));const di=idx("部門","category","department"),ci=idx("工事コード","code"),ni=idx("工事名称","工事名","現場名","name"),vi=idx("台帳バージョン","version");if(ni<0)throw new Error("工事名称の列がありません");items=rows.map(r=>({department:String(r[di]||"その他"),code:String(r[ci]||""),name:String(r[ni]||"")}));if(vi>=0&&rows[0]?.[vi])version=String(rows[0][vi])}items=items.filter(x=>x.name);if(!items.length)throw new Error("工事データがありません");return {version,items,importedAt:now()}}
$("chooseLedger").onclick=()=>$("ledgerFile").click();
$("ledgerFile").onchange=async()=>{const f=$("ledgerFile").files[0];if(!f)return;try{const next=normalizeLedger(await f.text(),f.name);if(!confirm(`工事台帳 ${next.version}（${next.items.length}件）へ更新しますか？\n出面履歴は削除されません。`)){$("ledgerFile").value="";return}ledger=next;save(KEYS.ledger,ledger);renderUser();renderSites();alert("工事台帳を更新しました。")}catch(e){alert("工事台帳を読み込めませんでした。\n"+e.message)}finally{$("ledgerFile").value=""}};
function submissionState(date){const list=dayRecords(date,true),latest=submissions.filter(x=>x.workDate===date).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0],dirty=!latest||list.some(x=>x.updatedAt>latest.createdAt);return {list,latest,dirty}}
function renderSubmit(){const date=$("submitDate").value||localDate(),s=submissionState(date),active=s.list.filter(x=>!x.deleted),t=totals(active);$("submitPreview").innerHTML=`<b>${esc(date)}　${active.length}件</b><br>平時 ${DemaeCalc.display(t.normal)}／残業 ${DemaeCalc.display(t.ot)}／深夜 ${DemaeCalc.display(t.night)}`;$("submitState").textContent=!s.list.length?"この日の入力はありません。":s.latest&&!s.dirty?"本日分：共有実行済み":s.latest?"提出後に修正があります。再提出してください。":"本日分：未提出"}
$("submitDate").onchange=renderSubmit;
const csvColumns=["schemaVersion","recordId","revision","status","deleted","employeeId","employeeName","workDate","shift","workType","department","siteCode","siteName","startTime","endTime","normalMinutes","overtimeMinutes","nightMinutes","overtime100Minutes","overtime025Minutes","night025Minutes","normalDisplay","overtimeDisplay","nightDisplay","commute","transport","meals","specialA","specialB","note","createdAt","updatedAt"];
function csvEscape(v){const s=Array.isArray(v)?v.join("、"):String(v??"");return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function buildCsv(date){const list=dayRecords(date,true);if(!list.length)throw new Error("この日の入力はありません。");return "\uFEFF"+[csvColumns.join(","),...list.map(r=>csvColumns.map(k=>csvEscape(r[k])).join(","))].join("\r\n")}
function markShared(date,fileName){const list=dayRecords(date,true),isResubmission=submissions.some(x=>x.workDate===date);submissions.push({submissionId:uid(),employeeId:user.employeeId,workDate:date,type:isResubmission?"resubmission":"initial",recordIds:list.map(x=>x.recordId),recordCount:list.length,fileName,createdAt:now(),state:"shareOpened"});records.forEach(r=>{if(r.workDate===date){r.status="submitted";r.updatedAt=now()}});save(KEYS.submissions,submissions);save(KEYS.records,records);renderSubmit()}
function csvFile(date){const csv=buildCsv(date),name=`${user.employeeId}_${date.replaceAll("-","")}.csv`;return {name,file:new File([csv],name,{type:"text/csv;charset=utf-8"}),csv}}
$("shareCsv").onclick=async()=>{if(!user.employeeId||!user.recipientEmail){alert("社員番号と提出先メールアドレスを設定してください。");return}const date=$("submitDate").value;try{const x=csvFile(date);if(navigator.share&&navigator.canShare?.({files:[x.file]})){await navigator.share({files:[x.file],title:`電子出面 ${user.employeeId} ${date}`,text:`提出先：${user.recipientEmail}\n電子出面 ${date}`});markShared(date,x.name)}else{download(x);alert(`共有機能に対応していないためCSVをダウンロードしました。\n会社メールで ${user.recipientEmail} へ添付送信してください。`)}}catch(e){if(e.name!=="AbortError")alert(e.message)}};
function download(x){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([x.csv],{type:"text/csv;charset=utf-8"}));a.download=x.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("downloadCsv").onclick=()=>{try{const date=$("submitDate").value,x=csvFile(date);download(x);markShared(date,x.name)}catch(e){alert(e.message)}};
$("wipeAll").onclick=()=>{const entered=prompt("誤操作防止のため、現在の社員番号を入力してください。");if(entered===null)return;if(!user.employeeId||entered!==user.employeeId){alert("社員番号が違うため削除しませんでした。");return}if(!confirm("工事台帳、入力履歴、提出履歴をすべて削除します。\n提出していないデータがないことを確認してください。"))return;if(!confirm("最終確認です。本当にこの端末のデータを全削除しますか？"))return;Object.values(KEYS).forEach(k=>localStorage.removeItem(k));location.reload()};
setToday();renderUser();resetForm();renderHistory();renderSubmit();if(!user.employeeId||!user.name)show("settingsView");
})();
