(function(){
"use strict";
const APP_VERSION="2.6.6",SCHEMA_VERSION=2;
const KEYS={user:"demae.user",config:"demae.config",ledger:"demae.ledger",records:"demae.records",submissions:"demae.submissions",preferences:"demae.preferences",system:"demae.system"};
const $=id=>document.getElementById(id),now=()=>new Date().toISOString();
const localDate=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const envelope=(data)=>({schemaVersion:SCHEMA_VERSION,updatedAt:now(),data});
let storageFailure=false;
// V2.6.6: localStorage が次回起動時に空になった場合に備え、同じ内容を IndexedDB に二重保存する。
const MIRROR_DB="demae-resilient-v1",MIRROR_STORE="kv";
function mirrorDb(){return new Promise((resolve,reject)=>{if(!window.indexedDB){reject(new Error("IndexedDB unavailable"));return}const q=indexedDB.open(MIRROR_DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(MIRROR_STORE))q.result.createObjectStore(MIRROR_STORE)};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error||new Error("IndexedDB open failed"))})}
async function mirrorWriteRaw(rows){const db=await mirrorDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(MIRROR_STORE,"readwrite"),st=tx.objectStore(MIRROR_STORE);for(const [key,raw] of rows){if(raw===null)st.delete(key);else st.put(raw,key)}tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||new Error("IndexedDB write failed"));tx.onabort=()=>reject(tx.error||new Error("IndexedDB write aborted"))})}finally{db.close()}}
async function mirrorReadAll(){const db=await mirrorDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(MIRROR_STORE,"readonly"),st=tx.objectStore(MIRROR_STORE),out={};const q=st.openCursor();q.onsuccess=()=>{const c=q.result;if(c){out[c.key]=c.value;c.continue()}else resolve(out)};q.onerror=()=>reject(q.error||new Error("IndexedDB read failed"))})}finally{db.close()}}
function mirrorLater(rows){mirrorWriteRaw(rows).catch(e=>{console.error("mirror save failed",e);showStorageGuard("予備保存の確認に失敗しました。通常保存は残っていますが、山下さんへ連絡してください。","danger")})}
async function resilientStartup(){try{const backup=await mirrorReadAll(),localRecords=localStorage.getItem(KEYS.records),backupRecords=backup[KEYS.records];let backupCount=0;if(backupRecords){try{const x=JSON.parse(backupRecords);backupCount=Array.isArray(x?.data)?x.data.filter(r=>!r?.deleted).length:0}catch{}}
    if(localRecords===null&&backupCount>0){for(const [key,raw] of Object.entries(backup))localStorage.setItem(key,raw);showStorageGuard(`端末の通常保存が空になっていたため、予備保存から入力履歴 ${backupCount}件を自動復旧しました。`,"success");setTimeout(()=>location.reload(),1200);return "recovered"}
    const seed=Object.values(KEYS).map(key=>[key,localStorage.getItem(key)]).filter(([,raw])=>raw!==null);if(seed.length)await mirrorWriteRaw(seed);return "ok";
  }catch(e){console.error("resilient startup failed",e);showStorageGuard("予備保存機能を確認できませんでした。通常保存は利用できますが、山下さんへ連絡してください。","danger");return "mirror-failed"}}
function showStorageGuard(message,kind="danger"){const el=$("storageGuard");if(!el)return;el.className=`notice ${kind}`;el.textContent=message;el.classList.remove("hidden")}
function hideStorageGuard(){const el=$("storageGuard");if(el)el.classList.add("hidden")}
function load(key,fallback){const raw=localStorage.getItem(key);if(raw===null)return fallback;try{const obj=JSON.parse(raw);if(!obj||!("data" in obj))throw new Error("保存形式が不正です");return obj.data??fallback}catch(e){storageFailure=true;showStorageGuard("保存済みデータの読込に異常を検出しました。新しい入力をせず、山下さんへ連絡してください。", "danger");console.error("storage load failed",key,e);return fallback}}
function rawSnapshot(keys){const s={};keys.forEach(k=>s[k]=localStorage.getItem(k));return s}
function restoreSnapshot(snapshot){let ok=true;for(const [k,v] of Object.entries(snapshot)){try{if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);if(localStorage.getItem(k)!==v)ok=false}catch(e){ok=false;console.error("storage rollback failed",k,e)}}return ok}
function saveBundle(entries){const rows=entries.map(([key,data])=>[key,JSON.stringify(envelope(data))]),snapshot=rawSnapshot(rows.map(x=>x[0]));try{for(const [key,raw] of rows)localStorage.setItem(key,raw);for(const [key,raw] of rows)if(localStorage.getItem(key)!==raw)throw new Error(`保存後の再読込不一致: ${key}`);mirrorLater(rows);return true}catch(e){storageFailure=true;const restored=restoreSnapshot(snapshot);showStorageGuard(restored?"この端末で保存確認に失敗しました。変更前の状態へ戻しました。このまま入力せず、山下さんへ連絡してください。":"保存失敗後の復旧確認にも失敗しました。この端末では入力を続けないでください。山下さんへ連絡してください。", "danger");console.error("storage bundle save failed",e);return false}}
function save(key,data){return saveBundle([[key,data]])}
function storageSelfTest(){const key="demae.storageProbe",value=`${Date.now()}-${Math.random()}`;try{localStorage.setItem(key,value);const ok=localStorage.getItem(key)===value;localStorage.removeItem(key);if(!ok)throw new Error("readback mismatch");return true}catch(e){storageFailure=true;showStorageGuard("この端末では電子出面データを安全に保存できない可能性があります。このまま入力せず、山下さんへ連絡してください。", "danger");console.error("storage self test failed",e);return false}}
function isIOS(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||((navigator.platform||"")==="MacIntel"&&navigator.maxTouchPoints>1)}
function isStandalone(){return navigator.standalone===true||window.matchMedia?.("(display-mode: standalone)")?.matches===true}
function currentMode(){return isStandalone()?"ホーム画面版":"Safari版"}
function applyFirstRunGuard(){const firstRun=!user.employeeId||!user.name;if(isIOS()){const mode=currentMode();const msg=firstRun?`【${mode}で初期設定できます】この画面のまま初期設定・工事台帳読込・入力ができます。Safari版とホーム画面版は保存領域が別になる場合があります。途中で使う方を変えるときは、設定の「データ引継ぎ」でバックアップ→読込をしてください。`:`現在は${mode}を使用中です。入力データはこのモード内に保存されます。Safari版とホーム画面版を切り替える場合は「データ引継ぎ」を使用してください。`;showStorageGuard(msg,"info")}return true}
function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
let user=load(KEYS.user,{}),config=load(KEYS.config,{workers:[],recipientEmail:""}),ledger=load(KEYS.ledger,{version:"未設定",items:[]}),records=load(KEYS.records,[]),submissions=load(KEYS.submissions,[]),prefs=load(KEYS.preferences,{transportHistory:[],lastSite:"",lastDepartment:"",lastCommute:0,lastTransport:[]});
prefs.transportHistory=Array.isArray(prefs.transportHistory)?prefs.transportHistory:[];
prefs.lastTransport=Array.isArray(prefs.lastTransport)?prefs.lastTransport:[];
let editingId=null,selectedTransport=[];
if(storageSelfTest())save(KEYS.system,{appVersion:APP_VERSION});
function esc(v){return String(v??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function show(view){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$(view).classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.view===view));if(view==="historyView"){renderHistory();renderSubmit()}}
document.querySelectorAll(".tab").forEach(x=>x.onclick=()=>show(x.dataset.view));
function setToday(){const month=localDate().slice(0,7);$("workDate").value=localDate();$("submitMonth").value=month;$("historyMonth").value=month}
function timeOptions(){return Array.from({length:48},(_,i)=>{const h=String(Math.floor(i/2)).padStart(2,"0"),m=i%2?"30":"00",v=`${h}:${m}`;return `<option value="${v}">${v}</option>`}).join("")}
$("startTime").innerHTML=timeOptions();$("endTime").innerHTML=timeOptions();
function setTime(id,value){const el=$(id);if(![...el.options].some(o=>o.value===value)){const o=document.createElement("option");o.value=value;o.textContent=`${value}（旧入力）`;el.appendChild(o)}el.value=value}
function setCommute(value){const raw=String(value??"").trim(),n=Number(raw);$("commute").value=raw!==""&&Number.isInteger(n)&&n>0&&n<=200?String(n):""}
function commuteValue(){const raw=$("commute").value.trim();return raw===""?0:Number(raw)}
function holidayCalendar(){return ledger.holidayCalendar||null}
function isHolidayDate(date){const c=holidayCalendar();return !!date&&Array.isArray(c?.holidays)&&c.holidays.includes(date)}
function isWorkType(workType){return !["雨休","特休","有給","欠勤"].includes(workType)}
function activeWorkDates(extraDate="",extraWorkType="通常"){const set=new Set(records.filter(r=>!r.deleted&&r.workDate&&r.startTime&&r.endTime&&isWorkType(r.workType||"通常")).map(r=>r.workDate));if(extraDate&&isWorkType(extraWorkType))set.add(extraDate);return [...set]}
function holidayDecision(workDate,workType="通常"){if(!isHolidayDate(workDate)||!isWorkType(workType))return "weekday";return DemaeCalc.holidayTreatment(workDate,activeWorkDates(workDate,workType)).treatment}
function calculationFor(start,end,workType,workDate,shift){const isHoliday=isHolidayDate(workDate),treatment=holidayDecision(workDate,workType);return DemaeCalc.calculate(start,end,workType,isHoliday,shift,treatment)}
function calc(){const c=calculationFor($("startTime").value,$("endTime").value,$("workType").value,$("workDate").value,$("shift").value);$("normalDisplay").textContent=c.normalDisplay;$("overtimeDisplay").textContent=c.overtimeDisplay;$("nightDisplay").textContent=c.nightDisplay;$("holidayDisplay").textContent=c.holidayDisplay||"0.0";return c}
function setShift(){if($("shift").value==="night"){setTime("startTime","20:00");setTime("endTime","05:00")}else if($("shift").value==="day"){setTime("startTime","08:00");setTime("endTime","17:00")}calc()}
[$("startTime"),$("endTime"),$("workDate")].forEach(x=>x.addEventListener("input",calc));$("workType").addEventListener("change",calc);$("shift").addEventListener("change",setShift);$("department").addEventListener("change",()=>{renderManagers();renderSites()});$("manager").addEventListener("change",renderSites);
function renderManagers(){const current=$("manager").value,dep=$("department").value,names=[...new Set(ledger.items.filter(x=>x.department===dep&&x.manager).map(x=>x.manager))].sort((a,b)=>a.localeCompare(b,"ja"));$("manager").innerHTML='<option value="">指定しない</option>';names.forEach(name=>{const o=document.createElement("option");o.value=name;o.textContent=name;$("manager").appendChild(o)});if(names.includes(current))$("manager").value=current}
function renderSites(){const current=$("site").value,dep=$("department").value,manager=$("manager").value;$("site").innerHTML='<option value="">現場なし</option>';ledger.items.filter(x=>x.department===dep&&(!manager||x.manager===manager)).forEach(x=>{const o=document.createElement("option");o.value=x.code;o.textContent=x.name;o.dataset.name=x.name;$("site").appendChild(o)});if([...$("site").options].some(x=>x.value===current))$("site").value=current;else if(prefs.lastSite&&[...$("site").options].some(x=>x.value===prefs.lastSite))$("site").value=prefs.lastSite}
function renderTransport(){$("transportHistory").innerHTML=prefs.transportHistory.map(x=>`<option value="${esc(x)}">`).join("");$("transportTags").innerHTML="";selectedTransport.forEach((name,i)=>{const b=document.createElement("button");b.type="button";b.className="tag";b.textContent=name+" ×";b.onclick=()=>{selectedTransport.splice(i,1);renderTransport()};$("transportTags").appendChild(b)});$("transportToggle").textContent=selectedTransport.length?`送迎：${selectedTransport.join("、")}`:"送迎を入力"}
$("transportToggle").onclick=()=>$("transportPanel").classList.toggle("open");$("transportAdd").onclick=()=>{const n=$("transportName").value.trim();if(!n)return;if(!prefs.transportHistory.includes(n))prefs.transportHistory.unshift(n);if(!selectedTransport.includes(n))selectedTransport.push(n);save(KEYS.preferences,prefs);$("transportName").value="";renderTransport()};
function selectedSiteName(){const o=$("site").selectedOptions[0];return o?.dataset.name||"現場なし"}
function resetForm(){editingId=null;$("editBanner").classList.add("hidden");$("saveRecord").textContent="入力を保存";$("workDate").value=localDate();$("shift").value="day";$("workType").value="通常";const lastItem=ledger.items.find(x=>x.code===prefs.lastSite),lastDepartment=lastItem?.department||prefs.lastDepartment;$("department").value=[...$("department").options].some(x=>x.value===lastDepartment)?lastDepartment:(user.department||"舗装");setCommute(prefs.lastCommute);$("meals").value=0;$("special").value="";$("note").value="";selectedTransport=[...prefs.lastTransport];$("transportPanel").classList.remove("open");setShift();renderManagers();$("manager").value="";renderSites();renderTransport()}
$("cancelEdit").onclick=resetForm;
$("saveRecord").onclick=()=>{
  if(!user.employeeId||!user.name){alert("先に設定画面で社員番号と氏名を登録してください。");show("settingsView");return}
  const commute=commuteValue();if(!Number.isInteger(commute)||commute<0||commute>200){alert("通勤は0～200の整数で入力してください。");return}
  const siteCode=$("site").value,note=$("note").value.trim(),absence=["雨休","特休","有給","欠勤"].includes($("workType").value);if(!siteCode&&!note&&!absence){alert("現場なしの場合は、摘要へ内容を入力してください。");return}
  const c=calc();if(!c.valid){alert(c.errorMessage);return}
  const sameShift=records.find(x=>!x.deleted&&x.recordId!==editingId&&x.workDate===$("workDate").value&&x.shift===$("shift").value);
  if(sameShift){const shiftLabel=$("shift").value==="night"?"夜":$("shift").value==="day"?"昼":"その他";if(!confirm(`${$("workDate").value}の${shiftLabel}勤務は既に入力されています。\n同じ区分をもう1件追加しますか？`))return}
  const previous=records.find(x=>x.recordId===editingId),stamp=now();
  const special=$("special").value;
  const r={recordId:editingId||uid(),schemaVersion:SCHEMA_VERSION,employeeId:user.employeeId,employeeName:user.name,workDate:$("workDate").value,targetMonth:$("workDate").value.slice(0,7),shift:$("shift").value,workType:$("workType").value,department:$("department").value,manager:$("manager").value,siteCode,siteName:selectedSiteName(),startTime:$("startTime").value,endTime:$("endTime").value,crossesMidnight:$("endTime").value<=$("startTime").value,breakMinutes:90,commute,transport:[...selectedTransport],meals:Number($("meals").value||0),specialA:special==="A"?1:0,specialB:special==="B"?1:0,note,...c,createdAt:previous?.createdAt||stamp,updatedAt:stamp,revision:(previous?.revision||0)+1,status:previous?.status==="submitted"?"modified":"draft",deleted:false};
  const nextRecords=previous?records.map(x=>x.recordId===r.recordId?r:x):[...records,r],nextPrefs={...prefs,lastSite:siteCode,lastDepartment:r.department,lastCommute:r.commute>0?r.commute:0,lastTransport:[...selectedTransport]};if(!saveBundle([[KEYS.records,nextRecords],[KEYS.preferences,nextPrefs]])){alert("入力を端末へ保存できませんでした。入力は完了していません。");return}records=nextRecords;prefs=nextPrefs;const verify=load(KEYS.records,[]).some(x=>x.recordId===r.recordId&&!x.deleted);if(!verify){storageFailure=true;showStorageGuard("保存直後の再読込に失敗しました。この入力は保存完了として扱えません。山下さんへ連絡してください。", "danger");alert("保存確認に失敗しました。この入力は保存完了ではありません。");return}resetForm();show("historyView");
};
function dayRecords(date,includeDeleted=false){return records.filter(x=>x.workDate===date&&(includeDeleted||!x.deleted))}
function latestPreviousWorkDate(date){
  return records.filter(x=>!x.deleted&&x.workDate<date).map(x=>x.workDate).sort((a,b)=>b.localeCompare(a))[0]||"";
}
function applyCopiedRecord(r){
  $("shift").value=r.shift||"day";$("workType").value=[...$("workType").options].some(x=>x.value===r.workType)?r.workType:"通常";
  $("department").value=r.department||user.department||"舗装";renderManagers();const ledgerItem=ledger.items.find(x=>x.code===r.siteCode);$("manager").value=r.manager||ledgerItem?.manager||"";renderSites();$("site").value=r.siteCode||"";
  setTime("startTime",r.startTime||"08:00");setTime("endTime",r.endTime||"17:00");setCommute(r.commute);
  $("meals").value=String(r.meals||0);$("special").value=r.specialA?"A":r.specialB?"B":"";$("note").value=r.note||"";
  selectedTransport=[...(r.transport||[])];renderTransport();calc();
  alert(`${r.workDate}の入力をコピーしました。\n日付は${$("workDate").value}のままです。内容を確認して保存してください。`);
}
function copyPrevious(){
  if(editingId){alert("修正中は「前日と同じ」を使用できません。入力クリア後に使用してください。");return}
  const date=$("workDate").value,previous=latestPreviousWorkDate(date);
  if(!previous){alert(`${date}より前の保存済み入力はありません。`);return}
  const list=dayRecords(previous).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));
  let chosen=list[0];
  if(list.length>1){
    const options=list.map((r,i)=>`${i+1}：${r.shift==="night"?"夜":"昼"}／${r.siteName||"現場なし"}／${r.startTime}～${r.endTime}`).join("\n");
    const answer=prompt(`${previous}には${list.length}件あります。\nコピーする番号を入力してください。\n\n${options}`,"1");
    if(answer===null)return;const index=Number(answer)-1;if(!Number.isInteger(index)||!list[index]){alert("正しい番号を入力してください。");return}chosen=list[index];
  }
  applyCopiedRecord(chosen);
}
$("copyPreviousTop").onclick=copyPrevious;
function displayValues(r){if(r.startTime&&r.endTime&&r.workDate)return calculationFor(r.startTime,r.endTime,r.workType||"通常",r.workDate,r.shift||"day");return {normalMinutes:Number(r.normalMinutes||0),overtimeMinutes:Number(r.overtimeMinutes||0),nightMinutes:Number(r.nightMinutes||0),holidayMinutes:Number(r.holidayMinutes||0),normalDisplay:r.normalDisplay||DemaeCalc.display(r.normalMinutes||0),overtimeDisplay:r.overtimeDisplay||DemaeCalc.display(r.overtimeMinutes||0),nightDisplay:r.nightDisplay||DemaeCalc.display(r.nightMinutes||0),holidayDisplay:r.holidayDisplay||DemaeCalc.display(r.holidayMinutes||0)}}
function totals(list){return list.reduce((a,r)=>{const v=displayValues(r),type=r.workType||"通常";a.days.add(r.workDate);if(type==="有給")a.paidLeave.add(r.workDate);if(type==="雨休")a.rainLeave.add(r.workDate);if(type==="欠勤")a.absence.add(r.workDate);a.normal+=Number(v.normalMinutes||0);a.ot+=Number(v.overtimeMinutes||0);a.night+=Number(v.nightMinutes||0);a.holiday+=Number(v.holidayMinutes||0);return a},{days:new Set(),paidLeave:new Set(),rainLeave:new Set(),absence:new Set(),normal:0,ot:0,night:0,holiday:0})}
function renderHistory(){const month=$("historyMonth").value,list=records.filter(x=>x.targetMonth===month&&!x.deleted).sort((a,b)=>b.workDate.localeCompare(a.workDate)||b.updatedAt.localeCompare(a.updatedAt)),t=totals(list);$("submitMonth").value=month;$("historySummary").textContent=`勤務日数 ${t.days.size}日／平時 ${DemaeCalc.display(t.normal)}／残業 ${DemaeCalc.display(t.ot)}／深夜 ${DemaeCalc.display(t.night)}／休日 ${DemaeCalc.display(t.holiday)}`;$("historyList").innerHTML=list.length?"":'<div class="card">この月の入力はありません。</div>';list.forEach(r=>{const v=displayValues(r),d=document.createElement("div");d.className="record";const state=r.status==="submitted"?'<span class="badge sent">提出済み</span>':r.status==="modified"?'<span class="badge">再提出必要</span>':'<span class="badge">未提出</span>';d.innerHTML=`<h3>${esc(r.workDate)}　${r.shift==="night"?"夜":"昼"} ${state}</h3><div class="history-grid"><div><small>区分</small>${esc(r.department)}</div><div class="site-cell"><small>工事名</small>${esc(r.siteName)}</div><div><small>勤務時間</small>${esc(r.startTime)}～${esc(r.endTime)}</div><div><small>平時</small>${esc(v.normalDisplay)}</div><div><small>残業</small>${esc(v.overtimeDisplay)}</div><div><small>深夜</small>${esc(v.nightDisplay)}</div><div><small>休日</small>${esc(v.holidayDisplay||"0.0")}</div><div><small>通勤</small>${esc(r.commute)}</div><div><small>送迎</small>${esc((r.transport||[]).join("、")||"")}</div></div><p>${esc(r.note)}</p><div class="record-actions"><button class="btn sub edit">編集</button><button class="btn danger remove">削除</button></div>`;d.querySelector(".edit").onclick=()=>editRecord(r.recordId);d.querySelector(".remove").onclick=()=>deleteRecord(r.recordId);$("historyList").appendChild(d)})}
$("historyMonth").onchange=()=>{renderHistory();renderSubmit()};
function editRecord(id){const r=records.find(x=>x.recordId===id);if(!r)return;editingId=id;$("editBanner").classList.remove("hidden");$("saveRecord").textContent="修正を保存";$("workDate").value=r.workDate;$("shift").value=r.shift;$("workType").value=r.workType;$("department").value=r.department;renderManagers();const ledgerItem=ledger.items.find(x=>x.code===r.siteCode);$("manager").value=r.manager||ledgerItem?.manager||"";renderSites();$("site").value=r.siteCode;setTime("startTime",r.startTime);setTime("endTime",r.endTime);setCommute(r.commute);$("meals").value=r.meals;$("special").value=r.specialA?"A":r.specialB?"B":"";$("note").value=r.note;selectedTransport=[...(r.transport||[])];renderTransport();calc();show("inputView")}
function deleteRecord(id){const r=records.find(x=>x.recordId===id);if(!r||!confirm("この入力を削除しますか？"))return;let nextRecords,message="";if(r.status==="submitted"||r.status==="modified"){nextRecords=records.map(x=>x.recordId===id?{...x,deleted:true,status:"deleted",updatedAt:now(),revision:(x.revision||0)+1}:x);message="提出済みの記録です。この月を再提出してください。"}else nextRecords=records.filter(x=>x.recordId!==id);if(!save(KEYS.records,nextRecords)){alert("削除結果を保存できなかったため、削除していません。");return}records=nextRecords;if(message)alert(message);renderHistory()}
function renderUser(){const preset=user.employeeId&&user.name?`${user.employeeId}|${user.name}`:"";$("employeePreset").innerHTML=config.workers.length?'<option value="">選択してください</option>':'<option value="">初期設定ファイルを読み込んでください</option>';config.workers.forEach(w=>{const o=document.createElement("option");o.value=`${w.employeeId}|${w.name}`;o.textContent=`${w.employeeId}　${w.name}`;$("employeePreset").appendChild(o)});$("employeePreset").value=[...$("employeePreset").options].some(x=>x.value===preset)?preset:"";$("employeeId").value=user.employeeId||"";$("employeeName").value=user.name||"";$("userDepartment").value=user.department||"舗装";$("recipientEmail").value=user.recipientEmail||config.recipientEmail||"";$("ledgerStatus").textContent=`現在の工事台帳：${ledger.version}（${ledger.items.length}件）／年間休日 ${ledger.holidayCalendar?.fiscalYear||"未設定"}年度（${ledger.holidayCalendar?.holidays?.length||0}日）`;$("statusLine").textContent=user.name?`${user.name}／台帳 ${ledger.version}`:"最初に利用者設定をしてください";$("currentWorker").textContent=user.name?`${user.employeeId} ${user.name}`:"未設定"}
$("employeePreset").onchange=()=>{const [id="",name=""]=$("employeePreset").value.split("|");$("employeeId").value=id;$("employeeName").value=name};
$("chooseSetup").onclick=()=>$("setupFile").click();
$("setupFile").onchange=async()=>{const f=$("setupFile").files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x.workers)||!x.workers.length||!x.recipientEmail)throw new Error("必要な設定がありません");const nextConfig={version:String(x.version||localDate()),workers:x.workers.map(w=>({employeeId:String(w.employeeId||""),name:String(w.name||"")})).filter(w=>w.employeeId&&w.name),recipientEmail:String(x.recipientEmail)};if(!nextConfig.workers.length)throw new Error("利用者がありません");if(!save(KEYS.config,nextConfig))throw new Error("端末への保存確認に失敗しました");config=nextConfig;renderUser();alert("初期設定を読み込みました。自分の名前を選んでください。")}catch(e){alert("初期設定ファイルを読み込めませんでした。\n"+e.message)}finally{$("setupFile").value=""}};
$("saveUser").onclick=()=>{const employeeId=$("employeeId").value.trim(),name=$("employeeName").value.trim(),recipientEmail=$("recipientEmail").value.trim();if(!employeeId||!name){alert("社員番号と氏名を入力してください。");return}const nextUser={employeeId,name,department:$("userDepartment").value,recipientEmail,initializedAt:user.initializedAt||now(),updatedAt:now()};if(!save(KEYS.user,nextUser)){alert("利用者設定を保存できませんでした。");return}user=nextUser;renderUser();resetForm();alert("利用者設定を保存しました。");};
function parseCsv(text){const rows=[];let row=[],cell="",quote=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'&&quote&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')quote=!quote;else if(ch===','&&!quote){row.push(cell);cell=""}else if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x!==""))rows.push(row);row=[];cell=""}else cell+=ch}row.push(cell);if(row.some(x=>x!==""))rows.push(row);return rows}
function normalizeLedger(raw,fileName){let version=localDate(),items=[];if(fileName.toLowerCase().endsWith(".json")){const obj=JSON.parse(raw);version=String(obj.version||obj.ledgerVersion||version);const list=Array.isArray(obj)?obj:(obj.items||obj.data||[]);items=list.map(x=>({department:String(x.department||x.category||x.部門||"その他"),code:String(x.code||x.工事コード||""),name:String(x.name||x.工事名称||x.工事名||""),manager:String(x.manager||x.担当者||x.監督名||"")}))}else{const rows=parseCsv(raw.replace(/^\uFEFF/,"")),head=rows.shift().map(x=>x.trim()),idx=(...names)=>head.findIndex(h=>names.includes(h));const di=idx("部門","category","department"),ci=idx("工事コード","code"),ni=idx("工事名称","工事名","現場名","name"),mi=idx("担当者","担当者名","監督名","manager"),vi=idx("台帳バージョン","version");if(ni<0)throw new Error("工事名称の列がありません");items=rows.map(r=>({department:String(r[di]||"その他"),code:String(r[ci]||""),name:String(r[ni]||""),manager:String(r[mi]||"")}));if(vi>=0&&rows[0]?.[vi])version=String(rows[0][vi])}items=items.filter(x=>x.name);if(!items.length)throw new Error("工事データがありません");const holidayCalendar=fileName.toLowerCase().endsWith(".json")?(JSON.parse(raw).holidayCalendar||null):null;if(!holidayCalendar||!Array.isArray(holidayCalendar.holidays)||!holidayCalendar.holidays.length)throw new Error("年間休日カレンダーが入っていません。V2.2用の工事台帳JSONを選んでください。");return {version,items,holidayCalendar,importedAt:now()}}
$("chooseLedger").onclick=()=>$("ledgerFile").click();
$("ledgerFile").onchange=async()=>{const f=$("ledgerFile").files[0];if(!f)return;try{const next=normalizeLedger(await f.text(),f.name);if(!confirm(`工事台帳 ${next.version}（${next.items.length}件）へ更新しますか？\n出面履歴は削除されません。`)){$("ledgerFile").value="";return}if(!save(KEYS.ledger,next))throw new Error("端末への保存確認に失敗しました");ledger=next;renderUser();renderSites();alert("工事台帳を更新しました。")}catch(e){alert("工事台帳を読み込めませんでした。\n"+e.message)}finally{$("ledgerFile").value=""}};
function monthRecords(month,includeDeleted=false){return records.filter(x=>x.targetMonth===month&&(includeDeleted||!x.deleted))}
function submissionState(month){const list=monthRecords(month,true),latest=submissions.filter(x=>x.targetMonth===month).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0],dirty=!latest||list.some(x=>x.updatedAt>latest.createdAt);return {list,latest,dirty}}
function renderSubmit(){const month=$("submitMonth").value||localDate().slice(0,7),s=submissionState(month),active=s.list.filter(x=>!x.deleted),t=totals(active);$("shareCsv").textContent=`${Number(month.slice(5,7))}月分を提出`;$("submitPreview").innerHTML=`<b>${esc(month)}　${active.length}件／勤務 ${t.days.size}日</b><br>平時 ${DemaeCalc.display(t.normal)}／残業 ${DemaeCalc.display(t.ot)}／深夜 ${DemaeCalc.display(t.night)}／休日 ${DemaeCalc.display(t.holiday)}<br><b>有給 ${t.paidLeave.size}日／雨休 ${t.rainLeave.size}日／欠勤 ${t.absence.size}日</b>`;$("submitState").textContent=!s.list.length?"この月の入力はありません。":s.latest&&!s.dirty?"この月は共有実行済みです。":s.latest?"提出後に修正・削除があります。再提出してください。":"この月は未提出です。"}
$("submitMonth").onchange=renderSubmit;
const csvColumns=["schemaVersion","recordId","revision","status","deleted","employeeId","employeeName","workDate","shift","workType","department","siteCode","siteName","startTime","endTime","normalMinutes","overtimeMinutes","nightMinutes","overtime100Minutes","overtime025Minutes","night025Minutes","holidayMinutes","holidayPremiumMinutes","holidayRate","isHoliday","holidayTreatment","holidayNeedsReview","holidayReviewReason","normalDisplay","overtimeDisplay","nightDisplay","commute","transport","meals","specialA","specialB","note","createdAt","updatedAt"];
function csvEscape(v){const s=Array.isArray(v)?v.join("、"):String(v??"");return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function csvRecord(r){return r.startTime&&r.endTime&&r.workDate?{...r,...calculationFor(r.startTime,r.endTime,r.workType||"通常",r.workDate,r.shift||"day")}:r}
function buildCsv(month){const list=monthRecords(month,true).sort((a,b)=>a.workDate.localeCompare(b.workDate)||a.createdAt.localeCompare(b.createdAt));if(!list.length)throw new Error("この月の入力はありません。");return "\uFEFF"+[csvColumns.join(","),...list.map(r=>{const row=csvRecord(r);return csvColumns.map(k=>csvEscape(row[k])).join(",")})].join("\r\n")}
function markShared(month,fileName){const list=monthRecords(month,true),isResubmission=submissions.some(x=>x.targetMonth===month),sharedAt=now(),nextSubmissions=[...submissions,{submissionId:uid(),employeeId:user.employeeId,targetMonth:month,type:isResubmission?"resubmission":"initial",recordIds:list.map(x=>x.recordId),recordCount:list.length,fileName,createdAt:sharedAt,state:"shareOpened"}],nextRecords=records.map(r=>r.targetMonth===month&&!r.deleted?{...r,status:"submitted"}:r);if(!saveBundle([[KEYS.submissions,nextSubmissions],[KEYS.records,nextRecords]])){alert("提出履歴の保存確認に失敗しました。CSV送信後でも画面上は未提出のままにしています。山下さんへ連絡してください。");return false}submissions=nextSubmissions;records=nextRecords;renderSubmit();return true}
function csvFile(month){const csv=buildCsv(month),name=`電子出面_${user.employeeId}_${user.name}_${month.replace("-","")}.csv`;return {name,file:new File([csv],name,{type:"text/csv;charset=utf-8"}),csv}}
$("shareCsv").onclick=async()=>{if(!user.employeeId||!user.recipientEmail){alert("社員番号と提出先メールアドレスを設定してください。");return}const month=$("submitMonth").value,count=monthRecords(month).length;if(!confirm(`${month.replace("-","年")}月分の出面を提出します。\n対象：${count}件\n\n入力内容を確認しましたか？`))return;try{const x=csvFile(month);if(navigator.share&&navigator.canShare?.({files:[x.file]})){await navigator.share({files:[x.file],title:`【月次提出】電子出面 ${user.employeeId} ${user.name} ${month}`,text:`提出先：${user.recipientEmail}\n${month}分の電子出面です。`});markShared(month,x.name)}else{download(x);alert(`共有機能に対応していないためCSVを作成しました。\n会社メールで ${user.recipientEmail} へ添付送信してください。`)}}catch(e){if(e.name!=="AbortError")alert(e.message)}};
function download(x){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([x.csv],{type:"text/csv;charset=utf-8"}));a.download=x.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function buildTransferData(){const data={};Object.entries(KEYS).forEach(([name,key])=>{data[name]=load(key,null)});return {kind:"demae-transfer",schemaVersion:1,appVersion:APP_VERSION,exportedAt:now(),mode:currentMode(),data}}
function exportTransfer(){try{const payload=JSON.stringify(buildTransferData(),null,2);const id=(user.employeeId||"未設定").replace(/[^0-9A-Za-z_-]/g,"_");const name=`技能電子出面_引継ぎ_${id}_${localDate().replaceAll("-","")}.json`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([payload],{type:"application/json;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);alert("データ引継ぎファイルを保存しました。\n別のSafari／ホーム画面版で『引継ぎファイルを読み込む』を押してください。") }catch(e){alert("引継ぎファイルを作成できませんでした。\n"+e.message)}}
function validateTransfer(x){if(!x||x.kind!=="demae-transfer"||x.schemaVersion!==1||!x.data||typeof x.data!=="object")throw new Error("電子出面の引継ぎファイルではありません");const d=x.data;if(d.records!=null&&!Array.isArray(d.records))throw new Error("入力履歴の形式が不正です");if(d.submissions!=null&&!Array.isArray(d.submissions))throw new Error("提出履歴の形式が不正です");if(d.user!=null&&typeof d.user!=="object")throw new Error("利用者設定の形式が不正です");if(d.config!=null&&typeof d.config!=="object")throw new Error("初期設定の形式が不正です");if(d.ledger!=null&&typeof d.ledger!=="object")throw new Error("工事台帳の形式が不正です");return d}
function importTransfer(x){const d=validateTransfer(x),pairs=Object.entries(KEYS),recCount=Array.isArray(d.records)?d.records.filter(r=>!r?.deleted).length:0,who=d.user?.name?`${d.user.employeeId||""} ${d.user.name}`:"利用者未設定";if(!confirm(`引継ぎデータをこの${currentMode()}へ読み込みます。\n${who}／入力 ${recCount}件\n\n現在このモードにあるデータは引継ぎデータで置き換わります。続けますか？`))return false;const snapshot=rawSnapshot(pairs.map(([,key])=>key)),target={};try{for(const [name,key] of pairs)target[key]=Object.prototype.hasOwnProperty.call(d,name)&&d[name]!==null?JSON.stringify(envelope(d[name])):null;for(const [key,raw] of Object.entries(target)){if(raw===null)localStorage.removeItem(key);else localStorage.setItem(key,raw)}for(const [key,raw] of Object.entries(target))if(localStorage.getItem(key)!==raw)throw new Error(`引継ぎ後の再読込不一致: ${key}`);mirrorLater(Object.entries(target));if(!storageSelfTest())throw new Error("保存確認に失敗しました");alert("データを引き継ぎました。画面を再読み込みします。");location.reload();return true}catch(e){const restored=restoreSnapshot(snapshot);storageFailure=true;showStorageGuard(restored?"引継ぎに失敗したため、元のデータへ戻しました。":"引継ぎ失敗後の復旧確認にも失敗しました。入力を続けないでください。", "danger");alert((restored?"引継ぎに失敗したため、元のデータへ戻しました。":"引継ぎに失敗し、元データの復旧確認もできませんでした。山下さんへ連絡してください。")+"\n"+e.message);return false}}
$("exportTransfer").onclick=exportTransfer;
$("chooseTransfer").onclick=()=>$("transferFile").click();
$("transferFile").onchange=async()=>{const f=$("transferFile").files[0];if(!f)return;try{importTransfer(JSON.parse(await f.text()))}catch(e){alert("引継ぎファイルを読み込めませんでした。\n"+e.message)}finally{$("transferFile").value=""}};
function verifySavedData(){if(!storageSelfTest()){alert("保存状態の確認に失敗しました。入力を続けないでください。");return false}const checks=[[KEYS.user,x=>x&&typeof x==="object","利用者設定"],[KEYS.records,Array.isArray,"入力履歴"],[KEYS.submissions,Array.isArray,"提出履歴"],[KEYS.ledger,x=>x&&typeof x==="object"&&Array.isArray(x.items),"工事台帳"]];for(const [key,test,label] of checks){const raw=localStorage.getItem(key);if(raw===null)continue;const value=load(key,null);if(!test(value)){storageFailure=true;showStorageGuard(`${label}の保存状態に異常があります。入力を続けないでください。`,"danger");alert(`${label}の保存状態に異常があります。山下さんへ連絡してください。`);return false}}const count=Array.isArray(load(KEYS.records,[]))?load(KEYS.records,[]).filter(r=>!r?.deleted).length:0;showStorageGuard(`保存状態を確認しました。現在：${currentMode()}／入力履歴 ${count}件。`,"success");alert(`保存状態：確認済み\n${currentMode()}\n入力履歴 ${count}件`);return true}
$("checkStorage").onclick=verifySavedData;
$("wipeAll").onclick=()=>{const entered=prompt("誤操作防止のため、現在の社員番号を入力してください。");if(entered===null)return;if(!user.employeeId||entered!==user.employeeId){alert("社員番号が違うため削除しませんでした。");return}if(!confirm("工事台帳、入力履歴、提出履歴をすべて削除します。\n提出していないデータがないことを確認してください。"))return;if(!confirm("最終確認です。本当にこの端末のデータを全削除しますか？"))return;Object.values(KEYS).forEach(k=>localStorage.removeItem(k));mirrorWriteRaw(Object.values(KEYS).map(k=>[k,null])).finally(()=>location.reload())};
setToday();renderUser();resetForm();renderHistory();renderSubmit();storageSelfTest();applyFirstRunGuard();if(!user.employeeId||!user.name)show("settingsView");resilientStartup();
})();
